#!/bin/tcsh -f
set my_editor = "`printf "\""${0}"\"" | sed 's/.*\/\([^\.]\+\).*/\1/g'`"
switch ( "${my_editor}" )
case "connectED":
case "gedit":
	breaksw
case "vi":
case "vim":
case "vim-enhanced":
default:
	set my_editor = `printf "%s -p" "vim-enhanced"`
	breaksw
endsw

${my_editor} "./podcasts/science/naked-scientists.opml" "./radiocasts/bbc.co.uk/stations.lst" "./radiocasts/bbc.co.uk/update.tcsh" "./radiocasts/bbc.co.uk/url-regex.vim"

