		<outline title='Neo Hoo Doo Studios' xmlUrl='' type='rss' text='Neo Hoo Doo Studios' htmlUrl='http://neohoodoo.libsyn.com/' description=''/>,
				'19 Nocturne Boulevard'=>"http://neohoodoo.libsyn.com/rss/nocturne",
				'The Unspeakable and the Inhuman'=>"http://neohoodoo.libsyn.com/rss/unspeakable",
				''=>"",
				''=>"",
			),
			'tags'=>"",
		),
		<outline title='Broken Sea Audio&#39;s Website' xmlUrl='' type='rss' text='Broken Sea Audio&#39;s Website' htmlUrl='http://brokensea.com/' description=''/>,
				'Feedback: A Hero&#039;s Calling'=>'http://brokensea.com/feedback/feed/',
				'Doctor Who'=>"http://brokensea.com/drwho/feed/",
				'Star Trek: Archimedes'=>"http://brokensea.com/archimedes/feed/",
				'Ulysses Galactic Guides and Bounties Inc.'=>"http://www.brokensea.com/ulysses/feed/",
				'Hyborean Saga'=>'http://brokensea.com/hyboreansagas/feed/',
				'Maudelayne'=>'http://brokensea.com/maudelayne/feed/',
				'Jake Sampson: Monster Hunter'=>'http://brokensea.com/jakesampson/feed/'
				'Greenpond'=>'http://brokensea.com/greenpond/feed/',
				'G.U.S.U.'=>'http://brokensea.com/gusu/feed/',
				'Electric Grasshopper'=>'http://brokensea.com/electricgrasshopper/feed/',
			),
			'tags'=>"",
		),
		<outline title='Darker Projects' xmlUrl='' type='rss' text='Darker Projects' htmlUrl='http://darkerprojects.com/' description=''/>,
				'Quantum Retribution'=>"http://darkerprojects.com/feeds/Quantum_Retribution.xml",
				'Star Trek &ndash; Lost Frontier'=>"http://feeds.feedburner.com/Star-Trek-Lost-Frontier",
				'Tales From The Museum'=>"http://darkerprojects.com/feeds/Tales_From_The_Museum.xml",
				'Dark Matter'=>"http://darkerprojects.com/feeds/DarkMatter.xml",
				'Alive Inside'=>"http://darkerprojects.com/feeds/AliveInside.xml",
				'Far Horizons'=>"http://darkerprojects.com/feeds/FarHorizons.xml",
				'Falcon Banner'=>"http://darkerprojects.com/feeds/FalconBanner.xml",
				'Sword Of Windsor'=>"http://darkerprojects.com/feeds/SwordOfWindsor.xml",
				'Night Terrors'=>"http://darkerprojects.com/feeds/NightTerrors.xml",
				'Byron Chronicles'=>"http://darkerprojects.com/feeds/ByronChronicles.xml",
				'Beta Flight'=>"http://brokensea.com/betaflight/feed",
			),
			'tags'=>"",
		),
		<outline title='Circus-13 Productions' xmlUrl='' type='rss' text='Circus-13 Productions' htmlUrl='http://www.circus13productions.com/' description=''/>
		'Cross Mass Productions'=>array(
			'www'=>"http://cossmass.co.uk/",
			'info'=>array(
				'default'=>"",
				'Estalvins Legacy'=>"Ranging across the many parallel, and not so parallel, alternate realities of the Cossmass. Things aren't right in the greater reality know as the Cossmass. It encompasses thousands upon thousands of alternate realities. The stability of the Cossmass has been weakening.",
				'Estalvins Legacy'=>"http://feeds.feedburner.com/cossmass%2festalvinslegacy?format=xml",
				'Rebels of the Red Planet'=>"http://feeds.feedburner.com/cossmass/rebelsredplanet?format=xml",
		<outline title='Darker Projects&#39;' xmlUrl='' type='rss' text='Darker Projects&#39;' htmlUrl='http://darkerprojects.com/' description=''/>,
				'Quantum Retribution'=>"http://darkerprojects.com/feeds/Quantum_Retribution.xml",
				'Star Trek &ndash; Lost Frontier'=>"http://feeds.feedburner.com/Star-Trek-Lost-Frontier",
				'The Section 31 Files'=>"http://feeds.feedburner.com/TheSection31Files?format=xml",
				'Pioneers'=>"http://feeds.feedburner.com/startrekpioneers?format=xml",
				'Tales From The Museum'=>"http://darkerprojects.com/feeds/Tales_From_The_Museum.xml",
				'Dark Matter'=>"http://darkerprojects.com/feeds/DarkMatter.xml",
				'Alive Inside'=>"http://darkerprojects.com/feeds/AliveInside.xml",
				'Far Horizons'=>"http://darkerprojects.com/feeds/FarHorizons.xml",
				'Falcon Banner'=>"http://darkerprojects.com/feeds/FalconBanner.xml",
				'Sword Of Windsor'=>"http://darkerprojects.com/feeds/SwordOfWindsor.xml",
				'Night Terrors'=>"http://darkerprojects.com/feeds/NightTerrors.xml",
				'Byron Chronicles'=>"http://darkerprojects.com/feeds/ByronChronicles.xml",
		<outline title='Curious Echoes' xmlUrl='' type='rss' text='Curious Echoes' htmlUrl='http://www.curiousecho.org/wordpress/category/moon-wraith/' description=''/>,
				'Moon Wraith'=>"http://www.curiousecho.org/wordpress/category/moon-wraith/feed",
		<outline title='Pendant Productions' xmlUrl='' type='rss' text='Pendant Productions' htmlUrl='http://www.pendantaudio.com/' description=''/>,
				'Seminar'=>"http://www.pendantaudio.com/seminar-podcast.xml",
				'Batman: The Ace of Detectives'=>"http://www.pendantaudio.com/batman_podcast.xml",
				'Umket Industries Presents: The Dixie Stenberg and Brassy Battalion Adventure Theater'=>"http://www.pendantaudio.com/dixie-podcast.xml",
