<?php	return array(
		''=>array(
			'www'=>"",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		'The Linux Action Show'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/TheLinuxActionShowOGG?format=xml",
			),
			'tags'=>"",
		),
		'Lug Radio Live'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://lugradio.org/episodes.ogg.rss",
			),
			'tags'=>"",
		),
		'hashlugradio'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/hashlugradio-ogg?format=xml",
			),
			'tags'=>"",
		),
		'Sourcetrunk'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/sourcetrunk_ogg?format=xml",
			),
			'tags'=>"",
		),
		'Novel Open Audio'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.novell.com/feeds/openaudio/?feed=rss2&cat=13&format=ogg",
			),
			'tags'=>"",
		),
		'OSC'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.gigavox.com/gigavox/channel/osc",
			),
			'tags'=>"",
		),
		'Linux Australia Round up'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://la-pod.k-sit.com/rss/la_pod_ogg.xml",
			),
			'tags'=>"",
		),
		'LUG Round up'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://la-pod.k-sit.com/rss/lug_roundup_ogg.xml",
			),
			'tags'=>"",
		),
		'Open Source on the Air'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://localfoss.org/taxonomy/term/64/0/feed",
			),
			'tags'=>"",
		),
		'Open News Show'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.opennewsshow.org/ogg.xml",
			),
			'tags'=>"",
		),
		'Linux Reality'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/linuxreality-ogg?format=xml",
			),
			'tags'=>"",
		),
		'the lip'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://thelip.net/?feed=atom",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		),
			'tags'=>"",
		'hack'=>array(
		'Hak.5'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://hak5xvid.libsyn.com/rss",
			),
			'tags'=>"",
		),
		'Systm'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://revision3.com/systm/feed/theora-small",
			),
			'tags'=>"",
		),
		'Digital Underground'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://digitalunderground.tv/feeds/du-divx.xml",
			),
			'tags'=>"",
		),
		'TWAT'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://twatech.org/wp-feed.php",
			),
			'tags'=>"",
		),
		'PaulDotCom'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://pauldotcom.com/podcast/psw.xml",
			),
			'tags'=>"",
		),
		'Binary Revolution Radio'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.binrev.com/radio/podcast/",
			),
			'tags'=>"",
		),
		'the broken'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://revision3.com/thebroken/feed/theora-small",
			),
			'tags'=>"",
		),
		'2600: Off the Hook'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.2600.com/oth-broadband.xml",
			),
			'tags'=>"",
		),
		'CyberSpeak'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://cyberspeak.libsyn.com/rss",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'tech; indie'=>array(
		'GeekMuse'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://geekmuse.net/podcast/",
			),
			'tags'=>"",
		),
		'Austech News'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/AustechNews?format=xml",
			),
			'tags'=>"",
		),
		'Best Damn Tech Show, Period!'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/BestDamnTechShowPeriodVideo?format=xml",
			),
			'tags'=>"",
		),
		'TechnoRama'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/ChuckChatTechnorama?format=xml",
			),
			'tags'=>"",
		),
		'Gadgetboyz'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Gadgetboyz?format=xml",
			),
			'tags'=>"",
		),
		'Casting From The Server Room'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/CastingFromTheServerRoom?format=xml",
			),
			'tags'=>"",
		),
		'In the Trenches'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://kevindevin.com/?feed=rss2&cat=2",
			),
			'tags'=>"",
		),
		'The Geekcast'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Geekcast?format=xml",
			),
			'tags'=>"",
		),
		'TreeNinjas'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.treeninjas.com/?feed=podcast",
			),
			'tags'=>"",
		),
		'Tech News Radio'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Technewsradio?format=xml",
			),
			'tags'=>"",
		),
		'TIMS (the independant media showcase)'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Timsreview?format=xml",
			),
			'tags'=>"",
		),
		'techIQ'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/techiq?format=xml",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'tech; professional'=>array(
		'dl.tv'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.ziffdavis.com/ziffdavis/dltvdivxvideo",
			),
			'tags'=>"",
		),
		'Cranky Geeks'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.ziffdavis.com/ziffdavis/cgipodvideo",
			),
			'tags'=>"",
		),
		'TWiT'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://leoville.tv/podcasts/twit-ogg.xml",
			),
			'tags'=>"",
		),
		'Macbreak Weekly'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://leoville.tv/podcasts/mbw.xml",
			),
			'tags'=>"",
		),
		'Extreme Tech'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.ziffdavis.com/ziffdavis/extremetechpodcast",
			),
			'tags'=>"",
		),
		'Whats New Now'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.ziffdavis.com/ziffdavis/wnnpodcast",
			),
			'tags'=>"",
		),
		'|Between the Lines|'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://blogs.zdnet.com/BTL/wp-rss2.php",
			),
			'tags'=>"",
		),
		'gear &middot; media &middot; tech'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://gearmediatech.libsyn.com/rss",
			),
			'tags'=>"",
		),
		'Engadget'=>array(
			'homepage'=>"http://podcasts.engadget.com/",
			'rss'=>array(
				'default'=>"http://podcasts.engadget.com/rss-ogg.xml",
			),
			'tags'=>"",
		),
		'IT Conversations'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.gigavox.com/gigavox/channel/itconversations",
			),
			'tags'=>"",
		),
		'Xeni Tech'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.npr.org/rss/podcast.php?id=4465031",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		),
			'tags'=>"",
		'c|net'=>array(
		'c|net live'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/cnet/cnetlive?format=xml",
			),
			'tags'=>"",
		),
		'Crave'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://podcasts.cnet.co.uk/CNET_co_uk_Podcast.rss",
			),
			'tags'=>"",
		),
		'c|net tv'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://reviews.cnet.com/html/xml/2001-12839_7-0.xml",
			),
			'tags'=>"",
		),
		'c|net news.com'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://news.com.com/2325-11424_3-0.xml",
			),
			'tags'=>"",
		),
		'the real deal'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.cnet.com/i/pod/realdeal.xml",
			),
			'tags'=>"",
		),
		'cnet.com.au videos'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.cnet.com.au/feeds/rss/?tag=latest_videos",
			),
			'tags'=>"",
		),
		'tech politics rundown'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://news.com.com/2325-12835_3-0.xml",
			),
			'tags'=>"",
		),
		'Security Bites'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://news.com.com/2325-12640_3-0.xml",
			),
			'tags'=>"",
		),
		'the buzz report'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.cnet.com/av/vcast/buzz_video.xml",
			),
			'tags'=>"",
		),
		'Crave'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://crave.cnet.com/av/vcast/crave.xml",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'geek'=>array(
		'East meets West'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.subbrilliant.com/emw/?feed=rss2",
			),
			'tags'=>"",
		),
		'Diggnation'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://revision3.com/diggnation/feed/theora-small",
			),
			'tags'=>"",
		),
		'GeekNights'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/GeekNights?format=xml",
			),
			'tags'=>"",
		),
		'Life-in-Hex'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.lifeinhex.com/podcast.xml",
			),
			'tags'=>"",
		),
		'Daily Vlog'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/thedailyvlog?format=xml",
			),
			'tags'=>"",
		),
		'GeekCred'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/geekcred?format=xml",
			),
			'tags'=>"",
		),
		'geek acres'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.geekacres.libsyn.com/rss",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		'forGood'=>array(
		'NetSquared'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/libsyn/NetSquared?format=xml",
			),
			'tags'=>"",
		),
		'501c3cast'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/501c3cast?format=xml",
			),
			'tags'=>"",
		),
		'Australian Non-Profits'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Cpns-qut-nonprofitPodcasts?format=xml",
			),
			'tags'=>"",
		),
		'Hey Josh'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/joshshipp?format=xml",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		),
			'tags'=>"",
		'Science'=>array(
		'TERRA'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/Terravideos?format=xml",
			),
			'tags'=>"",
		),
		'Dr. Karl&lsquo;s Magical Hour'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.abc.net.au/science/k2/podcast/drk_rss.xml",
			),
			'tags'=>"",
		),
		'NASA Edge'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.nasa.gov/rss/NASAEdge_vodcast.rss",
			),
			'tags'=>"",
		),
		'NASA Cast'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.nasa.gov/rss/NASAcast_vodcast.rss",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'crafty'=>array(
		'Crafty Pod'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://feeds.feedburner.com/craftypod?format=xml",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'what\'s happening'=>array(
		'Hack Daily'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.abc.net.au/triplej/hack/podcast/hack_daily.xml",
			),
			'tags'=>"",
		),
		'Restoring the Balance'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.abc.net.au/triplej/restoringthebalance/podcast/restoring_the_balance.xml",
			),
			'tags'=>"",
		),
		''=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		)
		),
			'tags'=>"",
		'books'=>array(
		'Children of Rhatlan'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/104/book.xml",
			),
			'tags'=>"",
		),
		'Shadowmagic'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/92/book.xml",
			),
			'tags'=>"",
		),
		'Heaven: Season One'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/97/book.xml",
			),
			'tags'=>"",
		),
		'Heaven: Season Two - Hell'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/112/book.xml",
			),
			'tags'=>"",
		),
		'Heaven: Season Three - Earth'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/183/book.xml",
			),
			'tags'=>"",
		),
		'7th Son: Decent'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/53/book.xml",
			),
			'tags'=>"",
		),
		'7th Son: Deceit'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/103/book.xml",
			),
			'tags'=>"",
		),
		'7th Son: Destruction'=>array(
			'homepage'=>"",
			'rss'=>array(
				'default'=>"http://www.podiobooks.com/bookfeed/29127/192/book.xml",
			),
			'tags'=>"",
		),
	);
?>
