<?php	return array(
		''=>array(
			'www'=>"",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		'silentk::cbx33::pr0g80X.vid'=>array(
			'www'=>"http://progbox.co.uk/",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"http://progbox.co.uk/wordpress/?feed=podcast",
			),
			'tags'=>"",
		),
	);
?>
