<?php	return array(
		''=>array(
			'www'=>"",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"",
			),
			'tags'=>"",
		),
		'SonicSociety'=>array(
			'www'=>"http://www.sonicsociety.org/",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"http://sonic.libsyn.com/rss",
			),
			'tags'=>"",
		),
		'Escape Artists'=>array(
			'www'=>"http://escapeartists.net/",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"",
				'EscapePod'=>"http://escapepod.org/podcast.xml",
				'PseudoPod'=>"http://feeds.pseudopod.org/Pseudopod?format=xml",
				'PodCastle'=>"http://feeds.escapeartists.net/PodCastle_Main?format=xml",
			),
			'tags'=>"",
		),
		'Second Shift'=>array(
			'www'=>"http://www.secondshiftpodcast.com/",
			'irc'=>"",
			'stream'=>"",
			'rss'=>array(
				'default'=>"http://www.secondshiftpodcast.com/xml/2shift.xml",
			),
			'tags'=>"",
		),
	);
?>
