		<outline title='Buffy: Between the Lines' xmlUrl='http://buffybetweenthelines.com/?feed=rss2&cat=7' type='rss' text='Buffy: Between the Lines' htmlUrl='http://buffybetweenthelines.com/?cat=7' description=''/>
		<outline title='Stranger things' xmlUrl='http://www.strangerthings.tv/?feed=rss2' type='rss' text='Stranger things' htmlUrl='http://www.strangerthings.tv/' description=''/>
		<outline title='Dark Places' xmlUrl='' type='rss' text='Dark Places' htmlUrl='http://jillarroway.com/darkplaces/' description=''/>
		<outline title='Voices of Babylon' xmlUrl='http://www.voicesofbabylon.com/category/tes/feed/' type='rss' text='Voices of Babylon' htmlUrl='http://voicesofbabylon.com/' description=''/>
		<outline title='Radio Yesterday' xmlUrl='http://radioyesterday.chuckchat.com/rss.php' type='rss' text='Radio Yesterday' htmlUrl='http://radioyesterday.chuckchat.com/' description=''/>
		<outline title='The Dunesteef Audio Fiction Magazine' xmlUrl='http://feeds.feedburner.com/TheDunesteefAudioFictionMagazine?format=xml' type='rss' text='The Dunesteef Audio Fiction Magazine' htmlUrl='http://dunesteef.com/' description=''/>
		<outline title='365 Tomorrows&#39; Voices of Tomorrow' xmlUrl='http://voicesoftomorrow.libsyn.com/rss' type='rss' text='365 Tomorrows&#39; Voices of Tomorrow' htmlUrl='http://voicesoftomorrow.libsyn.com/' description=''/>
		<outline title='Variant Frequencies' xmlUrl='http://www.variantfrequencies.com/feed/' type='rss' text='Variant Frequencies' htmlUrl='http://www.variantfrequencies.com/' description=''/>
		<outline title='Children of The Gods' xmlUrl='http://childrenofthegods.net/rss.xml' type='rss' text='Children of The Gods' htmlUrl='http://childrenofthegods.net/' description=''/>
		<outline title='Variant Frequencies' xmlUrl='http://www.variantfrequencies.com/feed/' type='rss' text='Variant Frequencies' htmlUrl='http://www.variantfrequencies.com/' description=''/>
		<outline title='Children of The Gods' xmlUrl='http://childrenofthegods.net/rss.xml' type='rss' text='Children of The Gods' htmlUrl='http://childrenofthegods.net/' description=''/>
		<outline title='Radio Adventures Of Dr. Floyd' xmlUrl='http://www.doctorfloyd.com/blog/rss.xml' type='rss' text='Radio Adventures Of Dr. Floyd' htmlUrl='http://www.doctorfloyd.com/' description=''/>
		<outline title='Video Adventures Of Dr. Floyd' xmlUrl='http://www.doctorfloyd.com/video/rss.xml' type='rss' text='Video Adventures Of Dr. Floyd' htmlUrl='http://www.doctorfloyd.com/video/' description=''/>
		<outline title='Radio Adventures Of Dr. Floyd' xmlUrl='http://www.doctorfloyd.com/blog/rss.xml' type='rss' text='Radio Adventures Of Dr. Floyd' htmlUrl='http://www.doctorfloyd.com/' description=''/>
		<outline title='Video Adventures Of Dr. Floyd' xmlUrl='http://www.doctorfloyd.com/video/rss.xml' type='rss' text='Video Adventures Of Dr. Floyd' htmlUrl='http://www.doctorfloyd.com/video/' description=''/>
		<outline title='I Killed Awesomeman' xmlUrl='http://welltoldtales.com/tag/awesomeman/feed' type='rss' text='I Killed Awesomeman' htmlUrl='http://ikilledawesomeman.com/' description=''/>
		<outline title='Wormwood: A Serialized Mystery' xmlUrl='http://feeds.feedburner.com/WormwoodMystery?format=xml' type='rss' text='Wormwood: A Serialized Mystery' htmlUrl='http://wormwoodshow.com/' description=''/>
		<outline title='Second Shift' xmlUrl='http://secondshiftpodcast.com/xml/2shifthq.xml' type='rss' text='Second Shift' htmlUrl='http://www.secondshiftpodcast.com/' description=''/>
		<outline title='After Lives' xmlUrl='http://www.afterlives.net/afterlives.xml' type='rss' text='After Lives' htmlUrl='http://www.afterlives.net/' description=''/>
		<outline title='The Leviathan Chronicles' xmlUrl='http://www.leviathanchronicles.com/rss/podcasts.xml' type='rss' text='The Leviathan Chronicles' htmlUrl='http://www.leviathanchronicles.com/' description='The Leviathan Chronicles tracks Macallan Orsel, a young genetic scientist in present-day New York City who discovers that immortality is not a fool&#039;s fantasy, but rather a reality for a several factions of powerful immortals living among us.'/>
		<outline title='Star Trek: Diplomatic Relations' xmlUrl='http://feeds.feedburner.com/StarTrekDiplomaticRelations?format=xml' type='rss' text='Star Trek: Diplomatic Relations' htmlUrl='http://www.startrekdiplomaticrelations.com/' description=''/>
		<outline title='Never Was' xmlUrl='http://www.podango.com/feeds/feed.php?pid=1360&amid=1&returnType=all' type='rss' text='Never Was' htmlUrl='http://www.mcleanweb.ca/neverwas/index.php' description=''/>
